CP-26401: Ported build from _oasis to jbuilder.
xapi-project/ocaml-xapi-plugin pull request #1
Opened 2017-12-27 16:52 UTC by kc284

Also, updated maintainers and re-indented.

Signed-off-by: Konstantina Chremmou <konstantina.chremmou@citrix.com>

2018-01-02 11:19 UTC, mseri approved these changes
Feel free to merge or modify the `Makefile` and then merge. Does this require specfile changes? It probably will require updating some `jbuild/_oasis` file to use `xapi-plugin` instead of `xapi_plugin`

2018-01-02 11:19 UTC, mseri commented on Makefile
> +	git ls-files '*.ml*' '**/*.ml*' | xargs ocp-indent --syntax cstruct -i
`'*.ml*'` is enough, `ls-files` looks for the files recursively in the folders

2018-01-02 11:21 UTC, mseri requested changes
Can you please fix the travis build as well?

2018-01-03 16:01 UTC, kc284 commented
I did search but didn't find any references to xapi_plugin, so to my best belief only xs-opam needs an update.

2018-01-03 16:17 UTC, mseri commented
It is possible that nothing is using it

2018-01-08 15:59 UTC, mseri approved these changes

2018-01-10 09:43 UTC, merged